### ISSUE TITLE
Idea: Add actions to plug-in

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-BMW-CD#5] opened 2020-06-08 14:37 UTC
Leaving a note here as a reminder from the forums.
Available actions as far as I know (2019 US 5 Series gas): 

- [ ] Honk Horn
- [ ] Start Climate 
- [ ] Flash Lights
- [ ] Lock Doors

**Comment by FlyingDiver** [comment] 2020-06-08 14:40
Duplicate of #3

**Closed by FlyingDiver** 2020-06-08 14:40 UTC
